import flatty/hashy

echo hashy(1.int8)
echo hashy(1.uint8)
echo hashy(1.int16)
echo hashy(1.uint16)
echo hashy(1.int32)
echo hashy(1.uint32)
echo hashy(1.int64)
echo hashy(1.uint64)
echo hashy(1.float32)
echo hashy(1.float64)
echo hashy("the number one")
echo hashy("the number one, the number one")
echo hashy("the number one, the number one, the number one")
