name: Github Actions
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v5
    - uses: jiro4989/setup-nim-action@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - run: nim js -r tests/jstest.nim
    - run: nim js -r tests/jstest_jsbinny.nim
    - run: nim c -r tests/test_binny.nim
    - run: nim c -r tests/test_datetime.nim
    - run: nim c -r tests/test_flatty.nim
    - run: nim c -r tests/test_hashy.nim
    - run: nim c -r tests/test_hexprint.nim
    - run: nim c -r tests/test_memoryused.nim
    - run: nim c -r tests/test_objvar.nim
